[keyboard]
bindings = [{ action = "SpawnNewInstance", key = "Return", mods = "Super|Alt" }]

[selection]
save_to_clipboard = true

[scrolling]
history = 65535

[font]
size = 11

[font.normal]
family = "Monaco Nerd Font"
style = "Regular"

[font.bold]
family = "Roboto Mono"
style = "Bold"

[font.italic]
family = "Monaco Nerd Font"
style = "Italic"

[font.bold_italic]
family = "Monaco Nerd Font"
style = "Bold Italic"

[font.offset]
x = 0
y = 0

[font.glyph_offset]
x = 0
y = 0

[colors.primary]
background = "#000000"
foreground = "#DCDFE4"

[colors.cursor]
text = "#112a2a"
cursor = "#DCDFE4"

[colors.vi_mode_cursor]
text = "#112a2a"
cursor = "#00ff00"

[colors.search.matches]
foreground = "#000000"
background = "#1AE642"

[colors.search.focused_match]
foreground = "#000000"
background = "#ff00ff"

[colors.hints.start]
foreground = "#1d1f21"
background = "#1AE642"

[colors.hints.end]
foreground = "#1AE642"
background = "#1d1f21"

[colors.line_indicator]
foreground = "#00ff00"
background = "#1d1f21"

[colors.footer_bar]
background = "#731d8b"
foreground = "#ffffff"

[colors.selection]
text = "#112a2a"
background = "#1AE642"

[colors.normal]
black = "#282C34"
red = "#E06C75"
green = "#98C379"
yellow = "#E5C07B"
blue = "#61AFEF"
magenta = "#C678DD"
cyan = "#56B6C2"
white = "#DCDFE4"

[colors.bright]
black = "#282C34"
red = "#E06C75"
green = "#98C379"
yellow = "#E5C07B"
blue = "#61AFEF"
magenta = "#C678DD"
cyan = "#56B6C2"
white = "#DCDFE4"
