[keyboard]
bindings = [
    { action = "SpawnNewInstance", key = "Return", mods = "Super|Alt" },
]

[selection]
save_to_clipboard = true

[scrolling]
history = 65535

[font]
size = 11

[font.normal]
family = "Monaco Nerd Font"
style = "Regular"

[font.bold]
family = "Roboto Mono"
style = "Bold"

[font.italic]
family = "Monaco Nerd Font"
style = "Italic"

[font.bold_italic]
family = "Monaco Nerd Font"
style = "Bold Italic"

[font.offset]
x = 0
y = 0

[font.glyph_offset]
x = 0
y = 0

[colors.primary]
background = "#272822"
foreground = "#F8F8F2"

[colors.cursor]
text = "#112a2a"
cursor = "#DCDFE4"

[colors.vi_mode_cursor]
text = "#112a2a"
cursor = "#DCDFE4"

[colors.search.matches]
foreground = "#000000"
background = "#1AE642"

[colors.search.focused_match]
foreground = "#000000"
background = "#ff00ff"

[colors.hints.start]
foreground = "#1d1f21"
background = "#1AE642"

[colors.hints.end]
foreground = "#1AE642"
background = "#1d1f21"

[colors.line_indicator]
foreground = "#00ff00"
background = "#1d1f21"

[colors.footer_bar]
background = "#731d8b"
foreground = "#ffffff"

[colors.selection]
text = "#112a2a"
background = "#1AE642"

[colors.normal]
black = "#75715E"
red = "#F92672"
green = "#A6E22E"
yellow = "#F4BF75"
blue = "#66D9EF"
magenta = "#AE81FF"
cyan = "#2AA198"
white = "#F9F8F5"

[colors.bright]
black = "#272822"
red = "#F92672"
green = "#A6E22E"
yellow = "#F4BF75"
blue = "#66D9EF"
magenta = "#AE81FF"
cyan = "#2AA198"
white = "#F8F8F2"
